model:
  name: 'ResNet18' 
  hugginface_model: "hugginface"
  local_model_path: "jfasldjflj"
  use_preprocessor: True
  local_preprocessor: "path"
  enable_resize: True
  resize_size: 224
  yolo_model: True

attack:
  targeted: True
  target_list: [(),()] 
  
   
dataset:
  train_on_dataset: True
  dataset_name: true
  dataset_path: "path"
  

one_pixel:
  enable_attack: True
  steps: 10
  pixels : 1
  population_size: 100





carlini_weiner:
  enable_attack: True
  kappa: 0.01
  steps: 10000 
  load_attack: "path"


PGD:
  enable_attack: True
  steps: 10000
  load_attack: "path"


FGSM:
  enable_attack: True
  epsilon: 0.3
  steps: 10000
  load_attack: "path"


