
enable_gpu: true

model:
  name: 'Resnet Microsoft' #the Name you want to give to the model
  hugginface_model: "microsoft/resnet-50"
  batch_size : 16 # Batch size for trainin. If you have problems with memory, you can use a lower batch size.

dataset:
  dataset_path: "mrm8488/ImageNet1K-val"
  sample_number: 50  # Number of samples to use from the dataset for the evaluation
  random_seed: 2 # If you want  perform the test with the same data each time, set a random seed not equal to 0.
  image_feature_title: "image" #Check on the specification of the dataset to see the name of the feature that contains the image
  label_feature_title: "label"
  


embedding_models:
#  Only enable this one if you want to use the CLIP model.
# The model_name specified in the model category will not be used.
  clip_model_enable : False

one_pixel:
  enable_attack: False
  steps: 20
  pixels : 1
  population_size: 100

FGSM:
  enable_attack: False
  epsilon: 0.005

PGD:
  enable_attack: False
  epsilon: 0.3
  alpha: 0.1
  steps: 100

carlini_wagner:
  enable_attack: true
  c: 0.5
  kappa: 0.1
  steps: 100
  lr: 0.01 



