
enable_wandb: True

model:
  name: 'ResNet18' 
  hugginface_model: "hugginface"
  local_model_path: "jfasldjflj"
  use_preprocessor: True
  local_preprocessor: "path"
  enable_resize: True
  resize_size: 224

dataset:
  train_on_dataset: True # If train on dataset is true it will use the true labels from the dataset. If it is set to False
                         # it will run the model with the images and generate pseudo labels to use for training.
  dataset_path: "imagenet-1k"
  sample_number: 100  # Number of samples to use from the dataset



embedding_models:
  clip_model_enable : True
  # Coco dataset labels
  sample_text_data : ['person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train', 'truck', 'boat', 'traffic light',
         'fire hydrant', 'stop sign', 'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow',
         'elephant', 'bear', 'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee',
         'skis', 'snowboard', 'sports ball', 'kite', 'baseball bat', 'baseball glove', 'skateboard', 'surfboard',
         'tennis racket', 'bottle', 'wine glass', 'cup', 'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple',
         'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 'cake', 'chair', 'couch',
         'potted plant', 'bed', 'dining table', 'toilet', 'tv', 'laptop', 'mouse', 'remote', 'keyboard', 'cell phone',
         'microwave', 'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase', 'scissors', 'teddy bear',
         'hair drier', 'toothbrush']


attack:
  targeted: False
  target_list: [(),()] 
  
  

one_pixel:
  enable_attack: True
  steps: 1000
  pixels : 1
  population_size: 100





carlini_weiner:
  enable_attack: False
  kappa: 0.01
  steps: 10000 
  load_attack: "path"


PGD:
  enable_attack: False
  steps: 10000
  load_attack: "path"


FGSM:
  enable_attack: True
  epsilon: 0.3
  steps: 10000
  load_attack: "path"


